---
title: "p8105_hw5_nh2706"
author: "Niklas Hess"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(patchwork)
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_chunk$set(
  fig.width = 10,
  fig.asp = .6,
  out.width = "95%")
```

# Problem 1 

Solutions provided!


# Problem 2

```{r}
raw_homicide_df = read_csv("./data/homicide-data.csv", na = c("","Unknown"))
skimr::skim(raw_homicide_df)
```


# Problem 3

```{r}

n = 30
sd = 5

true_mean = 0:6

dataset = function(x) {
  rnorm(n, x, sd)}

output = vector("list", length = 50)
inter <- data.frame(matrix(ncol = 3, nrow = 50))
colnames(inter) <- c('true_mean', 'sample_mean', 'p-value')



combine_function = function(y){
  inter2 = list()
  for (i in 1:50) {
    output[[i]] = dataset(y)
    a = broom::tidy(t.test(output[[i]]))
    inter[i,1] = y
    inter[i,2] = a[[1]]
    inter[i,3] = a[[3]]}
  inter2 = rbind(inter2, inter)}

final = map(true_mean, combine_function)
```

```{r}

df_final = data.frame(c(1:50),final[[1]])
for (i in 2:7) {
  df = data.frame(c(1:50),final[[i]])
  df_final = rbind(df_final, df)
  }

df_final = df_final %>%
  mutate(reject = ifelse(p.value < 0.05, TRUE, FALSE))

```



```{r}
reject_plot = df_final %>%
  group_by(true_mean) %>% 
  summarize(power = sum(reject)/50) %>% 
  ggplot(aes(x = true_mean, y = power)) +
  geom_point(aes(colour = true_mean)) +
  geom_line(alpha = 0.3) +
  labs(x = "True Mean", 
       y = "Proportion of times  null was rejected") +
  scale_x_continuous(breaks = seq(0,6,by = 1)) +
  scale_y_continuous(limits = c(0,1), breaks = seq(0,1,by = 0.2))

reject_plot
```


```{r}
Comparison_plot = df_final %>%
  group_by(true_mean) %>%
  summarize(mean_sample = mean(sample_mean)) %>%
  ggplot(aes(x = true_mean, y = mean_sample)) +
  geom_point(aes(colour = true_mean)) +
  labs(title = "Total Sample",
       x = "True Mean", 
       y = "Sample Mean") +
  scale_x_continuous(limits = c(0,6), breaks = seq(0,6,1)) +
  scale_y_continuous(limits = c(-2,7), breaks = seq(-2,7,1)) +
  theme(plot.title = element_text(hjust = 0.5))

Comparison_reject = df_final %>%
  group_by(true_mean) %>%
  filter(p.value < 0.05) %>%
  summarize(mean_sample = mean(sample_mean)) %>%
  ggplot(aes(x = true_mean, y = mean_sample)) +
  geom_point(aes(colour = true_mean)) +
  labs(title = "Rejected Null Sample",
       x = "True Mean", 
       y = "Sample Mean") +
  scale_x_continuous(limits = c(0,6), breaks = seq(0,6,1)) +
  scale_y_continuous(limits = c(-2,7), breaks = seq(-2,7,1)) +
  theme(plot.title = element_text(hjust = 0.5))

Comparison_plot + Comparison_reject





```

```{r}

```

